const express = require('express');
const router = express.Router();
const { criarProjeto, listarProjetos, buscarProjetoPorId, atualizarProjeto, deletarProjeto } = require('../application/handler/projetoHandler');
const { autenticarToken } = require('../middleware/authMiddleware');
router.post('/projetos', autenticarToken, criarProjeto);
router.get('/projetos', autenticarToken, listarProjetos);
router.get('/projetos/:id', autenticarToken, buscarProjetoPorId);
router.put('/projetos/:id', autenticarToken, atualizarProjeto);
router.delete('/projetos/:id', autenticarToken, deletarProjeto);
router.get('/projetos/:id/tarefas', autenticarToken);
module.exports = router;